/*
 * FILE: src/types.ts
 * PURPOSE: Houses all TypeScript type and interface definitions for the entire application.
 * WHERE USED: Used across screens, contexts, hooks, and database modules to ensure strong typing
 *             and compile-time validation for Firebase models (Expenses, Chores, Groceries, Users, etc.).
 */

// Import the standard Timestamp class from Firestore SDK to handle dates and timezones reliably
import { Timestamp } from 'firebase/firestore';

/**
 * RootStackParamList defines the parameters expected by each route in our navigation stack.
 * If a route accepts parameters, we list the keys and types. If it doesn't, we specify 'undefined'.
 */
export type RootStackParamList = {
  // Login screen takes no props
  Login: undefined;
  // Household selection landing screen takes no props
  HouseholdSelection: undefined;
  // Household setup screen accepts optional parameters for navigation state (e.g. create or join forms)
  HouseholdSetup: { householdId?: string | null; activeTab?: 'create' | 'join'; code?: string };
  // Main operational app tabs container takes no props
  MainTabs: undefined;
  // User profile modal/screen takes no props
  Profile: undefined;
  // Tab screens — householdId is managed in HouseholdContext, so no params are required here:
  Dashboard: undefined;
  Grocery: undefined;
  Expenses: undefined;
  Chores: undefined;
  Chat: undefined;
};

/**
 * UserProfile represents the collection structure of a user document in Firestore.
 * Collection path: /users/{uid}
 */
export interface UserProfile {
  // The user's unique identification string generated by Firebase Auth
  uid: string;
  // The registered email address of the user
  email: string;
  // Display username chosen by the user
  username: string;
  // Optional contact telephone number
  phoneNumber?: string;
  // The ID of the household they currently belong to. If they haven't joined one yet, this is null.
  householdId: string | null;
  // ISO date string indicating when this user profile was created
  createdAt: string;
  // Device notification token used by Firebase Cloud Messaging (FCM) to deliver push notifications
  pushToken?: string;
  // The roommate's active status indicator shown on the dashboard (e.g., 'sleeping', 'away')
  status?: 'home' | 'out' | 'sleeping' | 'away';
  // Optional URI pointing to their profile picture stored in Firebase Storage
  photoUrl?: string;
}

/**
 * HouseholdDetailField represents custom text fields (like gate codes or notes)
 * defined by roommate groups in their home details dashboard.
 */
export interface HouseholdDetailField {
  // Unique generated identifier for the custom field
  id: string;
  // The title/label displaying on the UI (e.g., "Main Gate Code")
  label: string;
  // The actual text value stored (e.g., "1234")
  value: string;
  // The keyboard layout or display type for input fields (e.g. hide password fields)
  type: 'text' | 'password' | 'time' | 'phone' | 'link';
  // Icon name string matched to Vector Icons library
  icon: string;
}

/**
 * Household represents a shared living household or a temporary trip.
 * Collection path: /households/{id}
 */
export interface Household {
  // Unique document ID in Firestore
  id: string;
  // Display name of the household (e.g. "Flat 40B" or "Summer Trip 2026")
  name: string;
  // The UID of the user who originally created this household
  createdBy: string;
  // 6-digit random code used by other roommates to join this specific household
  inviteCode: string;
  // Array of UIDs belonging to all roommates registered in this household
  members: string[];
  // The calendar day of the month when bills reset and cycles renew (1-31)
  billingCycleStartDay?: number;
  // The type of household. 'roommate' represents static flats, 'travel' represents temporary trips
  type?: 'roommate' | 'travel';
  // Trip details containing metadata. Only populated if `type` is 'travel'.
  tripDetails?: {
    startDate?: string;     // ISO Date or string for trip start
    endDate?: string;       // ISO Date or string for trip end
    destination?: string;   // Holiday destination city/country
    hotelName?: string;     // Hotel/stay lodging name
    bookingRef?: string;    // Hotel booking reference ID
    hotelPhone?: string;    // Contact number for lodging
    hotelAddress?: string;  // Location address of accommodation
    distanceTraveled?: string; // Odometer reading input for trip analytics
  };
  // General household settings and details shared with all members
  info?: {
    wifiName?: string;          // Name of local router network (SSID)
    wifiPass?: string;          // Wireless network password
    trashArrivalTime?: string;  // Time format "HH:mm" indicating local garbage collection schedule
    landlordName?: string;      // Property landlord/broker contact name
    landlordPhone?: string;     // Landlord telephone number
    other?: string;             // Miscellaneous instructions text area
    details?: HouseholdDetailField[]; // Custom fields array defined dynamically
    homeLocation?: { latitude: number; longitude: number }; // Geolocation coordinates of the home
  };
  // Data retention settings to automatically delete records after trip completion
  retentionPolicy?: '7_days_trip_end' | '15_days_trip_end';
  // Computed ISO timestamp when this travel household expires and is scheduled for deletion
  expiresAt?: string;
}

/**
 * ItineraryItem represents an event or stop in the travel schedule.
 * Collection path: /households/{householdId}/itinerary/{id}
 */
export interface ItineraryItem {
  // Unique document ID in Firestore
  id: string;
  // Date string (e.g., "2026-07-15")
  date: string;
  // Time string (e.g., "14:30")
  time: string;
  // Activity title/description (e.g., "Lunch at Pier 39")
  activity: string;
  // Optional extra comments or coordinates
  notes?: string;
  // The UID of the user who proposed this travel activity
  proposedBy: string;
  // True if other roommates have agreed and approved this event
  approved: boolean;
  // Timestamp when the item was created in Firestore
  createdAt: any;
}

/**
 * PackingItem represents an item to be packed for travel.
 * Collection path: /households/{householdId}/packing/{id}
 */
export interface PackingItem {
  // Unique document ID in Firestore
  id: string;
  // Description name of the item (e.g., "Toothbrush")
  name: string;
  // Checkbox status. True if packed, false if pending.
  done: boolean;
  // Timestamp when the item was added
  createdAt: any;
}

/**
 * Activity represents audit trail notifications shown in the recent activity log.
 * Collection path: /households/{householdId}/activities/{id}
 */
export interface Activity {
  // Unique document ID in Firestore
  id: string;
  // Type identifier used to render specific icons (e.g., 'expense', 'chore', 'grocery')
  type: string;
  // Descriptive summary string (e.g., "Jeevan added a new chore: Clean Kitchen")
  title: string;
  // Username of the roommate who triggered this event
  userName: string;
  // Numerical amount value. Only populated for expense transactions.
  amount: number;
  // UID of the roomie who triggered the event
  userId: string;
  // Optional target UID (used for settlement activities to link recipient)
  targetUid?: string;
  // Firestore server timestamp of when this log was generated
  createdAt: Timestamp;
}

/**
 * Expense represents any shared bills, purchase splits, or peer settlements.
 * Collection path: /households/{householdId}/expenses/{id}
 */
export interface Expense {
  // Unique document ID in Firestore
  id: string;
  // Type indicator. 'expense' is a shared bill, 'payment' is a direct roommate-to-roommate settlement.
  type: 'expense' | 'payment';
  // Descriptive tag (e.g., "Electricity Bill" or "Pizza Split")
  title?: string;
  // The monetary value of the expense/payment
  amount: number;
  // Spending tag (e.g., "Utilities", "Food", "Rent")
  category?: string;
  // The UID of the roommate who paid the bill (Only used if `type` === 'expense')
  paidByUid?: string;
  // The display name of the roommate who paid
  payerName?: string;
  // Array of roomie UIDs who will share and split this cost
  splitAmong?: string[];
  // The UID of the payer transferring settlement money (Only used if `type` === 'payment')
  fromPaidUid?: string;
  // The UID of the payee receiving settlement money (Only used if `type` === 'payment')
  toReceivedUid?: string;
  // Timestamp when transaction was saved
  createdAt: Timestamp;
  // True if this bill recurringly drafts every month
  isRecurring?: boolean;
  // Key tracking the last month draft was generated (e.g., "2026-07") to prevent double billing
  lastDraftedMonth?: string;
  // True if this specific instance was auto-drafted from a recurring schedule template
  isDrafted?: boolean;
}

/**
 * GroceryItem represents shopping items needed by the home.
 * Collection path: /households/{householdId}/groceries/{id}
 */
export interface GroceryItem {
  // Unique document ID in Firestore
  id: string;
  // Description name of item (e.g. "Whole Milk")
  name: string;
  // Checkbox status. True if purchased, false if still needed.
  done: boolean;
  // Sorting category (e.g., "Dairy", "Produce", "Pantry")
  category: string;
  // Quantitative size required (e.g., "2 Liters" or "3 Packs")
  qty: string;
  // Estimated cost of the item
  price: number;
  // The display name or UID of the roommate who added the item
  addedBy: string;
  // True if the user checked the item and chose to log this cost as a shared expense
  expenseLogged?: boolean;
  // Firestore timestamp of when the item was added
  createdAt: Timestamp;
}

/**
 * Chore represents rotation tasks and house duties.
 * Collection path: /households/{householdId}/chores/{id}
 */
export interface Chore {
  // Unique document ID in Firestore
  id: string;
  // Title details of task (e.g., "Take out trash")
  title: string;
  // UID of the roomie currently designated to perform this chore
  assignedToUid: string;
  // Checkbox status. True if completed, false if pending.
  done: boolean;
  // Creator UID
  createdByUid: string;
  // Preferred time of completion (e.g. "18:00")
  time: string;
  // Target weekday if weekly, or "Daily" (e.g., "Monday", "Friday")
  day: string;
  // Creation date timestamp
  createdAt: Timestamp;
  // True if task automatically rotates assignments upon completion
  rotationEnabled?: boolean;
  // Array of roomie UIDs defining the rotation sequence (order of chore turns)
  rotationOrder?: string[];
  // Current index pointing to who has the chore turn in rotationOrder array
  currentRotationIndex?: number;
  // Flag indicating if a local or push notification reminder has already been sent
  reminderSent?: boolean;
  // Array of roommate UIDs who have inspected and acknowledged the chore
  seenBy?: string[];
  // Deadline date timestamp computed for chores (used for overdue check)
  targetDate?: Timestamp;
  // The local scheduler event ID (used to cancel scheduled local push alerts)
  notificationId?: string;
}

/**
 * Message represents a text chat entry in the household chatroom.
 * Collection path: /households/{householdId}/messages/{id}
 */
export interface Message {
  // Unique document ID in Firestore
  id: string;
  // Message payload text string
  text: string;
  // UID of the sender
  senderId: string;
  // Display name of the sender
  senderName: string;
  // Timestamp when the message was sent
  createdAt: Timestamp;
  // List of roommate UIDs who have read this message (used to display read-receipts)
  readBy?: string[];
}
